import random

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z','0', '1', '2', '3', '4', '5', '6', '7', '8', '9','!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the Python Password Generator!")
print("-----------------------------------------------------------")
name = input("What is your name? : ")
print(f"{name}, How many character would you like in your password? :")
v = int(input("")) 
print("-----------------------------------------------------------")
sequence = random.sample(letters,v)
password = "".join(sequence)
random.shuffle(sequence)
print("your required suggested password is :" +  password)
print("-----------------------------------------------------------")